name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0,6,12 * * *"   # 每天 0 点 UTC 自动生成
  workflow_dispatch:       # 允许手动触发

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate 3D profile
        uses: yoshi389111/github-profile-3d-contrib@lastest
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}   # 更改为所有仓库权限（需要申请PAT）
          USERNAME: ${{ github.repository_owner }}
          MAX_REPOS: 1000

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "Generated 3D Contribution Graph" || echo "No changes to commit"
          git push
